defaultIndent: "   "

removeTrailingWhitespace:
  afterProcessing: 1

replacements:
  -
    substitution: s/ \s*/ /sg
  -
    substitution: |-
      s/
        ^(\s*)(.*?)\\tcblower(\n|)
      /
      $1$2
      $1%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      $1\\tcblower%
      $1%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      /sgx

specialBeginEnd:
  NiceMatrixCodeBefore:
    begin: '\\CodeBefore'
    end: '\\Body'
    lookForThis: 1

indentAfterItems:
  itemize: 1
  enumerate: 1
  enumerateNoVskip: 1
  description: 1
  list: 1
  tcbitemize: 1

lookForAlignDelims:
  tabularx:
    multiColumnGrouping: 1
  tabular:
    multiColumnGrouping: 1
  NiceTabular:
    multiColumnGrouping: 1
  NiceTabularX:
    delims: 1
    alignDoubleBackSlash: 1
    spacesBeforeDoubleBackSlash: 1
    multiColumnGrouping: 1

indentRules:
  item: 0       # needed because global rule should apply
  path: '   '
  draw: '   '
  node:
    body: '   '
    optionalArguments: '   '
    mandatoryArguments: '   '


# define special strings which are treated as parts of commands
# specially useful for proper TikZ support
commandCodeBlocks:
  roundedParenthesesAllowed: 1      # allow arguments in round parentheses
  stringsAllowedBetweenArguments:
    -
      amalgamate: 0     # don't combine this list with default list
    - 'at'
    - 'to'
    - 'node'
    - 'in'
    - '\+\+'
    - '\-\-'
    - 'rectangle'
    - 'circle'
    - 'ellipse'
    - 'cos'
    - 'sin'
    - ’\#\#\d’
  commandNameSpecial:
    -
      amalgamate: 0
    - '@ifnextchar\['

# if you want to use other names for your items (for example, \part)
# then populate them here; note that you can trick latexindent.pl
# into indenting all kinds of commands (within environments specified in 
# indentAfterItems) using this technique.
itemNames:
  item: 1
  myitem: 1
  tcbitem: 1

noAdditionalIndent:
  commands: 1
  emph: 1
  mandatoryArguments: 1

modifyLineBreaks:
  preserveBlankLines: 1
  condenseMultipleBlankLinesInto: 1
  textWrapOptions:
    columns: 70
    multipleSpacesToSingle: 1            
    blocksFollow:
        headings: 1
        commentOnPreviousLine: 1
        par: 1
        blankLine: 1
        verbatim: 1
        filecontents: 1
        other: '\\\]|\\item(?:\h|\[)'      # regex
    blocksBeginWith:
        A-Z: 1
        a-z: 1
        0-9: 0
        other: 0                           # regex
    blocksEndBefore:
        commentOnOwnLine: 1
        verbatim: 1
        filecontents: 1
        other: '\\begin\{|\\\[|\\end\{'    # regex
    huge: overflow                        # forbid mid-word line breaks
    separator: ""
  removeParagraphLineBreaks:
    beforeTextWrap: 1
    paragraphsStopAt:
      comments: 1
  commands:
    CommandStartsOnOwnLine: 0
    CommandNameFinishesWithLineBreak: 0
  mandatoryArguments:
    LCuBStartsOnOwnLine: 0
    MandArgBodyStartsOnOwnLine: 0
    RCuBStartsOnOwnLine: 0
    RCuBFinishesWithLineBreak: 0
  optionalArguments:
    tcolorbox:
      LSqBStartsOnOwnLine: 0
      OptArgBodyStartsOnOwnLine: 1
      RSqBStartsOnOwnLine: 1
      CommaFinishesWithLineBreak: 1
    scope:
      LSqBStartsOnOwnLinei<: 0
      OptArgBodyStartsOnOwnLine: 1
      RSqBStartsOnOwnLine: 1
      CommaFinishesWithLineBreak: 1
    tikzpicture:
      LSqBStartsOnOwnLine: 0
      OptArgBodyStartsOnOwnLine: 1
      RSqBStartsOnOwnLine: 1
      CommaFinishesWithLineBreak: 1
    tcbitemize:
      LSqBStartsOnOwnLine: 0
      OptArgBodyStartsOnOwnLine: 1
      RSqBStartsOnOwnLine: 1
      CommaFinishesWithLineBreak: 1
    tcbraster:
      LSqBStartsOnOwnLine: 0
      OptArgBodyStartsOnOwnLine: 1
      RSqBStartsOnOwnLine: 1
      CommaFinishesWithLineBreak: 1
  items:
    ItemStartsOnOwnLine: 1
    ItemFinishesWithLineBreak: 2
  environments:
    BeginStartsOnOwnLine: 2
    BodyStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 2
    EndStartsOnOwnLine: 2
    DBSFinishesWithLineBreak: 2
